$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: entaoaienv
image: akshata13/chatpdfenv:latest
inference_config:
  liveness_route:
    port: 8080
    path: /health
  readiness_route:
    port: 8080
    path: /health
  scoring_route:
    port: 8080
    path: /score